//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Product
    {
        public int ProductID { get; set; }
        public Nullable<int> CatID { get; set; }
        public Nullable<int> SubCatID { get; set; }
        public Nullable<int> BrandID { get; set; }
        public Nullable<int> SizeID { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public string Price { get; set; }
        public string Image { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
